feat: pump and dump implementation
yral-dapp/hot-or-not-backend-canister pull request #485
Opened 2024-12-27 15:27 UTC by rupansh-sekar-yral

2025-01-06 05:37 UTC, ravi-sawlani-yral commented
Can we tag the relevant issue over here. I am missing context around the game.

2025-01-20 12:32 UTC, rupansh-sekar-yral commented
@ravi-sawlani-yral we also need to set `CanisterIdSnsLedger` in all subnet orchestrators and individual user canisters to the principal of the DOLLR ledger

2025-01-20 15:09 UTC, ravi-sawlani-yral requested changes

2025-01-20 15:09 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/pump_n_dump/mod.rs
> +        }
Should we use guard `is_caller_global_admin`. Fetching global admin principal is sometimes flaky.

2025-01-20 15:09 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/pump_n_dump/mod.rs
> +            Err(e)
Shoudln't we refund the amount if call was not successful.

2025-01-20 15:09 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/pump_n_dump/mod.rs
> +        Ok(())
Prefer using guard `is_caller_global_admin`

2025-01-20 15:09 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/pump_n_dump/mod.rs
> +        Ok(())
Prefer using guard `is_caller_global_admin`

2025-01-21 12:09 UTC, rupansh-sekar-yral commented on src/canister/individual_user_template/src/api/pump_n_dump/mod.rs
> +            Err(e)
This is what we're doing here, yes

2025-01-21 12:09 UTC, rupansh-sekar-yral commented on src/canister/individual_user_template/src/api/pump_n_dump/mod.rs
> +        }
this was mainly to enable testing with testcontainers. Safe to switch it to guard now

2025-01-23 10:23 UTC, ravi-sawlani-yral commented on src/canister/individual_user_template/src/api/canister_lifecycle/post_upgrade.rs
> +    let mut pump_n_dump_data_bytes = vec![0; heap_data_len];
Shouldn't we have to assign `heap_data_len` to new value here?

```suggestion
    upgrade_reader.read(&mut heap_data_len_bytes).unwrap();
    heap_data_len = u32::from_le_bytes(heap_data_len_bytes);
    let mut pump_n_dump_data_bytes = vec![0; heap_data_len];
```

2025-01-23 10:51 UTC, rupansh-sekar-yral commented on src/canister/individual_user_template/src/api/canister_lifecycle/post_upgrade.rs
> +    let mut pump_n_dump_data_bytes = vec![0; heap_data_len];
Great catch, i didn't notice at all

2025-01-23 12:02 UTC, ravi-sawlani-yral approved these changes

2025-01-23 12:03 UTC, merged